# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brian Viviers
email: hello@brianviviers.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Brian Viviers
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://brianviviers.co.uk" # the base hostname & protocol for your site
twitter_username: 
github_username:  BrianViviers
linkedin_username: brian-viviers-5626a84a
linkedin_href: https://uk.linkedin.com/in/brian-viviers-5626a84a
copyright: Copyright

# Build settings
markdown: kramdown
highlighter: rouge
encoding: utf-8
